# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0002_auto_20180324_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Brief Description'),
            preserve_default=False,
        ),
    ]
